version: "3"
services:
  app:
    container_name: myapp
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
      - /home/app/node_modules
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecret
